# Generated by Django 5.2 on 2025-05-01 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_memory'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='date_taken',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='memory',
            name='capsule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='main_app.capsule'),
        ),
    ]
