# Generated by Django 5.2 on 2025-05-08 02:22

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_memory_likes_alter_memory_user_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capsule',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='capsule_images/'),
        ),
        migrations.AlterField(
            model_name='capsule',
            name='is_locked',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='memory',
            name='audio',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(resource_type='raw'), upload_to='memory_audio/'),
        ),
        migrations.AlterField(
            model_name='memory',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(resource_type='image'), upload_to='memory_images/'),
        ),
        migrations.AlterField(
            model_name='memory',
            name='video',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(resource_type='video'), upload_to='memory_videos/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='profile_pictures/'),
        ),
    ]
