# Generated by Django 5.2 on 2025-05-09 01:10

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_capsule_cover_image_alter_capsule_is_locked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capsule',
            name='cover_image',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='cover'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='memory',
            name='audio',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='memory_audio'),
        ),
        migrations.AlterField(
            model_name='memory',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='memory_image'),
        ),
        migrations.AlterField(
            model_name='memory',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='memory_video'),
        ),
    ]
