# Generated by Django 5.2 on 2025-05-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_capsule_cover_image_alter_memory_audio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capsule',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='capsule',
            name='open_date',
            field=models.DateField(blank=True, help_text='Only required if this capsule is locked.', null=True),
        ),
    ]
