# Generated by Django 5.2 on 2025-05-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(blank=True, help_text='Profiles this user is following', related_name='followers', to='main_app.profile'),
        ),
    ]
